repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: name-tests-test
-   repo: https://github.com/psf/black.git
    rev: 21.7b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort.git
    rev: v5.9.2
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/flake8.git
    rev: '3.9.2'
    hooks:
    -   id: flake8