version: "2.1"
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile_codercom
    image: vprzybylo/code_server_cocpit:v1.0.0
    container_name: code-server-cocpit
    environment:
      - PUID=1001
      - PGID=1001
      - DEFAULT_WORKSPACE=/data/data
      - TZ=America/New_York
#    shm_size: '100G'
    user: ${UID_GID}
    volumes:
      - /home/vanessa/:/home/vanessa
      - /raid/vanessa/cocpit:/data/data/
      - ${HOME}/.local/share/code-server/:/home/vanessa/.local/share/code-server
      - ${PWD}:/home/coder/project
#    deploy:
#      resources:
#        limits:
#          cpus: '20'
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [ gpu ]
#              device_ids: [ '6,7' ]
    ports:
      - 8443:8443
      - 8050:8050
    restart: unless-stopped
