version: "2.1"
services:
  code-server:
    build:
        context: .
        dockerfile: Dockerfile_codercom
    image: vprzybylo/code_server:v0.0.0
    container_name: code-server-vanessa
    environment:
      - PORT=8443 code-server
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    shm_size: '256G'
    user: ${UID_GID}
    volumes:
      - /raid/data/:/data/data/
      - $PWD/.config:/home/coder/.config
      - $HOME:/home/coder/project
    deploy:
        resources:
           limits:
                cpus: '10'
           reservations:
                devices:
                    - driver: nvidia
                      capabilities: [ gpu ]
                      device_ids: ['5,6']
    ports:
      - 8443:8443
    restart: unless-stopped

  cocpit:
    image: vprzybylo/cocpit_dev:v1.4.0
    container_name: jupyter_cocpit_dev
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /raid/data/:/data/data/
    ports:
      - 8889:8889
    shm_size: '256G'
    user: ${UID_GID}
    runtime: nvidia
    deploy:
        resources:
            limits:
                cpus: '10'
            reservations:
                devices:
                    - driver: nvidia
                      capabilities: [ gpu ]
                      device_ids: ['5,6']
    restart: unless-stopped
