FROM python:3.9-slim-buster
WORKDIR /data/data

LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all

RUN apt-get -y update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
SHELL ["/bin/bash", "-c"]
RUN source /root/.iterm2_shell_integration.bash
RUN apt-get -y update && apt-get install -y --no-install-recommends \
	python3-setuptools tesseract-ocr nodejs gcc git vim ffmpeg libsm6 sudo python3-pip \
	&& apt-get clean all

RUN groupadd -o -g 1001 vanessa \
        && useradd -o -r -m -u 1001 -g 1001 vanessa

RUN pip3 install --upgrade pip

COPY requirements_dev.txt /requirements_dev.txt
RUN pip3 install -r /requirements_dev.txt
EXPOSE 8889 8051

RUN jupyter lab build -y
CMD ["sh","-c", "jupyter lab --notebook-dir=/data/data/ --ip=0.0.0.0 --no-browser --allow-root --port=8889 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'"]
