FROM lscr.io/linuxserver/code-server
#working dir for the container, change to where your files live
WORKDIR /data/data


# set up NVIDIA drivers - allow all gpus (device id's specified when starting container)
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/bin/:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all

# install apt-get dependencies, node for imgcat through shell integration in iterm
# allows you to view images in terminal
RUN apt-get -y update && apt-get install -y curl wget
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get -y update && apt-get install -y --no-install-recommends \
	python3-setuptools python3.9 nodejs gcc git vim ffmpeg libsm6 sudo python3-pip \
	&& apt-get clean all && rm -rf /var/lib/apt/lists/*

# install python requirements
RUN pip3 install --upgrade pip
COPY requirements_dev.txt /requirements_dev.txt
RUN pip3 install -r /requirements_dev.txt

# run as user inside container
RUN groupadd -o -g 1001 vanessa \
        && useradd -o -r -m -u 1001 -g 1001 vanessa

# port for code-server to run on
EXPOSE 8443
