FROM python:3.9-slim-buster
WORKDIR /data/data

LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all

RUN apt-get -y update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get -y update && apt-get install -y --no-install-recommends \
	python3-setuptools nodejs gcc git vim ffmpeg libsm6 sudo python3-pip \
	&& apt-get clean all && rm -rf /var/lib/apt/lists/*

RUN groupadd -o -g 1001 vanessa \
        && useradd -o -r -m -u 1001 -g 1001 vanessa

RUN pip3 install --upgrade pip

RUN pip3 install tensorflow tensorflow-datasets jupyterlab pandas numpy matplotlib scikit-learn
EXPOSE 8890

RUN jupyter lab build -y
CMD ["sh","-c", "jupyter lab --notebook-dir=/data/data/ --ip=0.0.0.0 --no-browser --allow-root --port=8890 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'"]
