FROM arm64v8/python:3.9

RUN apt-get -y update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get -y update && apt-get install -y --no-install-recommends \
        wget \
        python3-setuptools \
        python3-sphinx \
        nodejs \
        gcc \
        git \
        vim \
        make \
        ffmpeg \
        libsm6 \
        sudo \
        python3-pip \
        && apt-get clean all && rm -rf /var/lib/apt/lists/*

RUN groupadd -o -g 1001 vanessa \
        && useradd -o -r -m -u 1001 -g 1001 vanessa

RUN pip3 install --upgrade pip
COPY requirements_dev.txt requirements_dev.txt
RUN pip3 install -r requirements_dev.txt

# install cocpit package for dev
COPY setup.py setup.py
COPY README.md README.md
RUN pip3 install -e .

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
         /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH
